:: ------------------------------------------------------------------- ::
:: Created by 136MasterNR, Read the "copyright.txt" file for more info ::
:: ------------------------------------------------------------------- ::

::                                                           !!!! WARNING !!!!                                                         ::
:: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ::
::                                                                                                                                     ::
:: (!) DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING - EDITING ANYTHING IN HERE MAY CAUSE MISS BEHAVIOR AND CAUSE PROBLEMS  ::
::     ON YOUR COMPUTER (!)                                                                                                            ::
:: (!) IF ANYONE TOLD YOU TO COPY AND PASTE CODE IN HERE OR DOWNLOAD ADDITIONAL FILES, THEY ARE MOST LIKELY TRYING TO SCAM YOU,        ::
::     UNLESS YOU ARE A TESTER AND THE OFFICIAL DEVELOPERS TOLD YOU TO DO SO (!)                                                       ::
::                                                                                                                                     ::
:: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ::
::                                                                                                                                     ::

:: :::::::::: ::
:: DOS Config ::
@SET OCD=%CD%
@PUSHD "%~dp0"
@TITLE Battles of Batch
@CHCP 65001 >NUL
@VERIFY OFF
@ECHO OFF
@SET COLS=117
@SET LINES=48
@SETLOCAL ENABLEDELAYEDEXPANSION
:: DOS Config ::
:: :::::::::: ::

ECHO.[3 q[?25l[-] Preparing ...
FOR /F "TOKENS=4-5DELIMS= " %%I IN ('VER') DO SET WINVER=%%I
IF NOT "=%WINVER:~0,3%" == "=10." (
	CLS
	ECHO.You are NOT running a supported OS or OS Version.
	PAUSE>NUL
	EXIT 1
)

:: Check if game is already running by trying to access its error logging file.
DEL /Q ".\data\logs.txt" 1>NUL 2>NUL
IF EXIST ".\data\logs.txt" (
	ECHO.[X] Already running, failed to launch
	ECHO.Game was already running at %TIME%>>".\data\logs.txt"
	EXIT 1
)

IF NOT %1.==READY. IF %1.==LAUNCH. (
	CLS
	TITLE Launcher
	ECHO.This is the game's launcher, do not close.
	START /WAIT "Launcher" "conhost.exe" -- "%~dpnx0" READY
	ECHO.Shutting down...
	(TASKKILL /F /FI "WINDOWTITLE eq WSAudio*" /IM "cmd.exe" /T | FINDSTR ":" && (
		TASKKILL /F /FI "WINDOWTITLE eq Administrator:  WSAudio*" /IM "cmd.exe" /T
	))
	TASKKILL /F /IM "easyrp.exe" /T
	TASKKILL /F /FI "WINDOWTITLE eq Now Live Logging - *" /IM "cmd.exe"
	EXIT 0
) ELSE (
	(IF EXIST ".\data\scripts\invisible.vbs" (
		START "wscript.exe" ".\data\scripts\invisible.vbs" "%~dpnx0" LAUNCH
	) ELSE (
		START /MIN "Launcher" conhost.exe -- "%~dpnx0" LAUNCH
	)) && (ECHO.[√] Launched!) || (ECHO. There was an unexpected error, failed to launch [X])
	EXIT /B 0
)

::  Start the logger and check if accessible,
2>".\data\logs.txt" (
	SET RUNNING=TRUE
	CALL :MAIN
)
::   if not accessible then exit, else below command will be skipped.
IF DEFINED RUNNING (
	::If it enters this statement then throw an error,
	::this usually means that the game's main function has crashed.
	ECHO.Critical Error: MAIN crashed
	PAUSE>NUL
)
EXIT 1

:MAIN
:: Debug
IF EXIST LET.DEBUG (
	PUSHD ".\data\cmd"
	CMD /Q /C ".\debug.cmd" log
	POPD
)

:: Check if directory files are accessible, such as itself.
IF NOT EXIST "%~nx0" (
	CLS
	ECHO.ERR : Inaccessible Directory.
	ECHO.
	ECHO.Try the following:
	ECHO.1. Do not run the batch file within a zip file or any winrar format.
	ECHO.2. Make sure that the batch file has permissions to Read/Write in this directory.
	ECHO.3. Do not launch the batch file directly from a search bar or a run-in.
	ECHO.4. If you are using a shortcut, make sure you added the correct directory.
	ECHO.5. Try launching with administrator/elevated permissions.
	PAUSE>NUL
	EXIT

:: Check if the game can reach the directory.
:: This can be a problem if the directory contains characters that batch doesn't understand.
) ELSE IF NOT EXIST "%CD%" (
	CLS
	ECHO.ERR : Unreachable Directory.
	ECHO.
	ECHO.Try the following:
	ECHO.1. Move the game ^(the whole folder^) to a different location.
	ECHO.2. Make sure the directory's URL name includes ONLY latin characters.
	ECHO.3. Do not move it to shared folders or onedrive.
	PAUSE>NUL&EXIT
)

:: Checks if the directory was altered, this mostly happens when launched in a zip file.
IF NOT "%CD%"=="%OCD%" (
	CLS
	ECHO.ERR : Altered Directory.
	ECHO.
	ECHO.Try the following:
	ECHO.1. Make sure to extract the game from the zip file.
	ECHO.2. Bad shortcut options, such as working directory.
	ECHO.3. Do not launch from shared folders or onedrive.
	ECHO.4. Do not launch with Administrator Privileges.
	PAUSE>NUL&EXIT
)

:: Check whether the scripts are accessible.
FOR /F "TOKENS=*" %%I IN ('DIR /S /B /A-D ".\data\scripts"^&DIR /S /B /A-D ".\data\core"') DO IF NOT "%%~nI"=="" (
	TYPE "%%~dpnxI" >NUL || (
		CLS
		ECHO.[X] Access denied:
		ECHO."%%~dpnxI"
		>&2 ECHO.[X] Access denied: "%%~dpnxI"
		PAUSE
		EXIT /B 1
	)
)

:START
:: Window Dimensions ::
MODE CON:COLS=%COLS% LINES=%LINES%

ECHO.[B[-] Initializing ...[A[G[[38;2;163;255;177m√[0m] Preparing ...[B

:: System Variables ::
FOR /F "delims==" %%I IN ('SET ^| FINDSTR /I /V
	/C:"PROMPT"
	/C:"PSModulePath"
	/C:"USERDOMAIN"
	/C:"SystemRoot"
	/C:"HOMEPATH"
	/C:"HOMEDRIVE"
	/C:"APPDATA"
	/C:"ComSpec"
	/C:"COMPUTERNAME"
	/C:"USERNAME"
	/C:"SystemDrive"
') DO SET "%%I="

:: Library References ::
SET "Path=%~dp0data\core;%~dp0data\core\cmd;%SystemRoot%\system32"
SET "PATHEXT=.CMD;.BAT;.EXE;.COM;.VBS;.VBE"

:: Game Version Info ::
SET VERCODE=0500
SET VERS=v0.5.00
SET VERTYPE=DEMO

:: Variables Init ::
SET "DATA=%CD%\data"
SET "RAW=!DATA!\raw"
SET UI=menu

:: ANSI Colors Init ::
FOR /F "TOKENS=*DELIMS=" %%I IN ('TYPE "%RAW%\colors.ans"') DO SET %%I

ECHO.[-] Reading raw data ...[A[G[[38;2;163;255;177m√[0m][B

:: Raw Data Init ::
CALL INIT ALL

ECHO.[-] Reading player data ...[A[G[[38;2;163;255;177m√[0m][B

:: Player Data Init ::
CALL PLAYER INIT

ECHO.[-] Loading display ...[A[G[[38;2;163;255;177m√[0m][B

:: User Interface ::
:UI

set S.
pause

PUSHD "!DATA!\screens\!UI!"
CALL "!DATA!\screens\!UI!\!UI!.cmd"
POPD

GOTO :UI
